### ISSUE TITLE
Do you need a logo?

### ISSUE THREAD

**Issue by nunojesus** [martinavagyan/save-the-pandas#1]
Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by martinavagyan** [comment]
Hi @nunojesus, thanks for the suggestion, the project is currently developed for a hackathon, and it does not need a logo. I am sure there will be other ways we can collaborate, lets keep in touch!
